import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { projects } from '../../../data/portfolio';
import { Architecture } from '../../../components/architecture';
import { profile } from '../../../lib/site';
export function generateStaticParams() { return projects.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const project = projects.find(p => p.slug === slug); if (!project) return {}; return { title: project.title, description: project.description, alternates: { canonical: `/projects/${slug}` }, openGraph: { title: `${project.title} | Azqa Jafar`, description: project.description, url: `/projects/${slug}` } }; }
export default async function ProjectPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const index = projects.findIndex(p => p.slug === slug); if (index < 0) notFound(); const project = projects[index]; const next = projects[(index + 1) % projects.length];
  return <main id="main-content" className="case-study shell"><Link className="text-link" href="/#projects"><ArrowLeft size={16}/> All selected systems</Link><div className="case-heading"><p className="kicker">0{index + 1} / {project.category}</p><h1>{project.subtitle}</h1><p className="lead">{project.description}</p><div className="tags">{project.tech.map(tech => <span key={tech}>{tech}</span>)}</div></div><Architecture project={project} index={index}/><div className="case-columns"><section><h2>01 / The problem</h2><p>{project.problem}</p></section><section><h2>02 / The solution</h2><p>{project.solution}</p></section><section><h2>03 / Core features</h2><ul>{project.features.map(feature => <li key={feature}>{feature}</li>)}</ul></section><section><h2>04 / Engineering approach</h2><p>{project.decision}</p></section></div><section className="case-workflow"><h2>05 / Workflow</h2><ol>{project.flow.map((step, i) => <li key={step}><span>0{i + 1}</span><div><h3>{step}</h3><p>{project.details[i]}</p></div></li>)}</ol></section>{project.learning && <section className="case-note"><h2>What I learned</h2><p>{project.learning}</p></section>}<div className="case-note"><p>Explore more of my work and development activity.</p><a className="text-link" href={profile.github} target="_blank" rel="noopener noreferrer">Visit my GitHub profile <ArrowUpRight size={16}/></a></div><Link className="next-project" href={`/projects/${next.slug}`}><span>EXPLORE NEXT SYSTEM</span><strong>{next.title}<ArrowUpRight/></strong></Link></main>;
}
