import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ArrowDown, Download, Github, Linkedin, Mail, GraduationCap, Award, ArrowRight } from 'lucide-react';
import { Navigation } from '../components/navigation';
import { Reveal, Specialty } from '../components/motion';
import { Architecture } from '../components/architecture';
import { ContactForm } from '../components/contact-form';
import { projects, expertise, experience } from '../data/portfolio';
import { profile, siteUrl } from '../lib/site';
function Label({ children }: { children: React.ReactNode }) { return <div className="kicker"><span/>{children}</div>; }
export default function Home() {
  const schema = { '@context': 'https://schema.org', '@graph': [{ '@type': 'Person', '@id': siteUrl + '/#person', name: profile.name, jobTitle: 'AI & ML Engineer', url: siteUrl, image: siteUrl + '/images/azqa-jafar.png', sameAs: [profile.github, profile.linkedin], alumniOf: { '@type': 'CollegeOrUniversity', name: 'University of Okara' }, knowsAbout: ['Generative AI', 'RAG', 'AI Agents', 'Machine Learning', 'AI Backend Engineering'] }, { '@type': 'ScholarlyArticle', headline: profile.paper, url: profile.publication, datePublished: '2026-09-21', author: { '@id': siteUrl + '/#person' }, isPartOf: { '@type': 'Periodical', name: 'Ain Shams Engineering Journal' } }] };
  return <><Navigation/><main id="main-content"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g, '\\u003c') }}/>
    <section id="home" className="hero shell"><div className="hero-grid" aria-hidden="true"/><Reveal className="hero-copy"><div className="eyebrow">AZQA JAFAR <span> / </span> AI & ML ENGINEER</div><h1>Intelligence,<br/>engineered.<br/><em>From context<br className="desktop-break"/> to capability.</em></h1><p>I build AI systems that retrieve, reason, and act. Working across generative AI, agentic workflows, machine learning, and the backends that bring them together.</p><Specialty/><div className="actions"><a className="primary" href="#projects">Explore my work <ArrowUpRight size={17}/></a><a className="secondary" href="/Azqa_Jafar_CV.pdf" download><Download size={16}/> Download CV</a></div><div className="social"><a href={profile.github} target="_blank" rel="noopener noreferrer"><Github size={16}/> GitHub <ArrowUpRight size={12}/></a><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={16}/> LinkedIn <ArrowUpRight size={12}/></a></div></Reveal>
    <Reveal className="portrait"><div className="portrait-corner corner-top"/><div className="photo-frame"><Image src="/images/azqa-jafar.png" alt="Azqa Jafar, AI and ML Engineer" fill priority sizes="(max-width: 760px) 90vw, 42vw" className="photo"/><div className="photo-shade"/><div className="portrait-caption"><span>THE ENGINEER BEHIND THE SYSTEMS</span><strong>Azqa Jafar<span>↗</span></strong></div></div><div className="portrait-corner corner-bottom"/><div className="portrait-tag"><span className="status-dot"/> CONTEXT → REASONING → ACTION</div><div className="portrait-coordinate" aria-hidden="true">01 / HUMAN AT THE CORE</div></Reveal><a className="scroll-cue" href="#about"><ArrowDown size={14}/> DISCOVER THE WORK</a></section>
    <div className="signal shell"><div><GraduationCap/><p><strong>BS Software Engineering</strong><span>University of Okara · 2022–2026</span></p></div><div><span className="signal-number">3.89<span>/4.00</span></span><p><strong>Academic foundation</strong><span>Software engineering & AI</span></p></div><div><span className="signal-icon">↗</span><p><strong>Published researcher</strong><span>Ain Shams Engineering Journal</span></p></div></div>
    <section id="about" className="section shell about"><Reveal><Label>01 / ABOUT</Label><h2>From a good question<br/>to a <em>working system.</em></h2></Reveal><Reveal className="about-copy"><p className="lead">I’m Azqa, a Software Engineering graduate and AI & ML Engineer working across retrieval, agentic workflows, machine learning, and AI-powered backend systems.</p><p>My work connects the full application lifecycle: data preparation, model integration, APIs, testing, and user-facing experiences. I focus on retrieval quality, reliable integrations, and clear implementation.</p><a className="text-link" href="#experience">Explore my experience <ArrowRight size={16}/></a></Reveal></section>
    <section id="expertise" className="section shell"><div className="section-heading"><div><Label>02 / EXPERTISE</Label><h2>The toolkit behind<br/><em>the intelligence.</em></h2></div><p>Connected capabilities, from the first embedding to the application layer.</p></div><div className="skill-grid">{expertise.map(([title, ...skills], i) => <Reveal className="skill" key={title}><span className="skill-number">0{i + 1}</span><h3>{title}</h3><div className="tags">{skills.map(skill => <span key={skill}>{skill}</span>)}</div></Reveal>)}</div></section>
    <section id="experience" className="section shell"><Label>03 / EXPERIENCE</Label><h2>Engineering in practice.</h2><div className="timeline">{experience.map(job => <Reveal key={job.company}><article className="job"><div className="job-body"><h3>{job.role}</h3><p className="company">{job.company}</p><ul>{job.bullets.map(bullet => <li key={bullet}>{bullet}</li>)}</ul><div className="tags">{job.tech.map(tech => <span key={tech}>{tech}</span>)}</div></div><p className="job-date">{job.date}</p></article></Reveal>)}</div></section>
    <section id="projects" className="section shell projects"><div className="section-heading"><div><Label>04 / SELECTED AI SYSTEMS</Label><h2>Built to retrieve.<br/>Designed to <em>reason.</em></h2></div><p>A curated collection spanning agentic workflows, retrieval, intelligent monitoring, and deep-learning research.</p></div>{projects.map((project, index) => <Reveal key={project.slug}><article className={'project project-' + index}><div className="project-copy"><div className="project-index">0{index + 1}<span> / {project.category}</span></div><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{project.tech.slice(0, 6).map(tech => <span key={tech}>{tech}</span>)}</div><Link className="text-link" href={'/projects/' + project.slug}>Explore the system <ArrowUpRight size={17}/></Link></div><Architecture project={project} index={index}/></article></Reveal>)}</section>
    <section id="research" className="section shell"><Label>05 / RESEARCH</Label><Reveal className="research"><div className="research-copy"><div className="paper-tag"><span className="status-dot"/> PUBLISHED RESEARCH · 21 SEP 2026</div><h2>{profile.paper}</h2><p className="journal">Ain Shams Engineering Journal</p><p>A hierarchical deep-learning framework for five-class diabetic retinopathy grading using the APTOS dataset, with stability-driven normalization, regularization, and refined feature aggregation.</p><a className="primary" href={profile.publication} target="_blank" rel="noopener noreferrer">Read publication <ArrowUpRight size={17}/></a></div><div className="research-visual"><div className="research-rings" aria-hidden="true"><span/><span/><span/><span/></div><div className="research-metric"><span>REPORTED TEST ACCURACY</span><strong>98.91<em>%</em></strong><p>Five-class classification<br/>APTOS dataset</p></div><small>Research result reported in the supplied CV.<br/>Not a claim of clinical deployment.</small></div></Reveal></section>
    <section id="achievements" className="section shell"><Label>06 / EDUCATION & RECOGNITION</Label><h2>A foundation in <em>excellence.</em></h2><div className="recognition-grid"><Reveal className="education-card"><GraduationCap size={28}/><span className="card-eyebrow">UNIVERSITY OF OKARA · 2022–2026</span><h3>BS Software <br/>Engineering</h3><p className="grade">3.89 <span>/ 4.00 CGPA</span></p><p>Software engineering, databases, software quality, application development, and AI/ML.</p><div className="prior-education"><strong>Intermediate · ICS Physics</strong><span>2020–2022 · 950 / 1100 marks</span></div></Reveal><div className="awards"><Reveal className="award-card"><Award/><div><span className="card-eyebrow">ACADEMIC MERIT</span><h3>Prime Minister’s Youth<br/>Laptop Scheme — Phase I</h3><p>Selected on the basis of academic merit and eligibility during undergraduate studies.</p></div></Reveal><Reveal className="award-card"><Award/><div><span className="card-eyebrow">MERIT SCHOLARSHIP</span><h3>Honhaar Merit-Based<br/>Graduation Scholarship</h3><p>Recognition of academic merit, dedication, and sustained undergraduate performance.</p></div></Reveal></div></div></section>
    <section id="contact" className="section shell contact"><Reveal className="contact-copy"><Label>07 / LET’S CONNECT</Label><h2>Let’s build<br/><em>intelligent systems.</em></h2><p>For AI engineering opportunities, research collaborations, or a useful idea worth building.</p><a className="contact-email" href={'mailto:' + profile.email}>{profile.email}<ArrowUpRight size={20}/></a><div className="social"><a href={profile.linkedin} target="_blank" rel="noopener noreferrer"><Linkedin size={16}/> LinkedIn</a><a href={profile.github} target="_blank" rel="noopener noreferrer"><Github size={16}/> GitHub</a></div><a className="text-link" href="/Azqa_Jafar_CV.pdf" download><Download size={15}/> Download my CV</a></Reveal><Reveal><ContactForm/></Reveal></section>
  </main><footer className="shell"><div><a className="brand" href="#home">AJ<span>.</span></a><p>Azqa Jafar <span> / AI & ML Engineer</span></p></div><span>Designed & built for AI engineering.</span><div className="footer-links"><a href={profile.github} target="_blank" rel="noopener noreferrer" aria-label="GitHub"><Github size={16}/></a><a href={profile.linkedin} target="_blank" rel="noopener noreferrer" aria-label="LinkedIn"><Linkedin size={16}/></a><a href={'mailto:' + profile.email} aria-label="Email"><Mail size={16}/></a><span>© {new Date().getFullYear()}</span></div></footer></>;
}
